services:
  squid:
    build:
      context:  .
      dockerfile: dockerfile
    environment:
      USERNAME: ${USERNAME}
      PASS: ${PASS}
      REALM: ${REALM}
    container_name: squid
    volumes:
      - squid-data-folder:/var/spool/squid/
      - ./squid-logs:/var/log/squid:rw
    restart: no
    ports:
      - "3128:3128"
      - "3129:3129"

volumes:
  squid-data-folder: