services:
  squid:
    build:
      context:  squid
      dockerfile: Dockerfile
    environment:
      USERNAME: ${USERNAME}
      PASS: ${PASS}
      REALM: ${REALM}
    container_name: squid
    volumes:
      - squid-data-folder:/var/spool/squid/
      - ./squid-logs:/var/log/squid:rw
    restart: no
    ports:
      - "3128:3128"
      - "3129:3129"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      NGINX_HOST: ${NGINX_HOST}
    restart: no
    ports:
      - "80:80"
    container_name: nginx
  

volumes:
  squid-data-folder: