services:
  squid:
    build:
      context:  .
      dockerfile: dockerfile
      args:
        CERT_FINGERPRINT: ${CERT_FINGERPRINT}
    environment:
      USERNAME: ${USERNAME}
      PASS: ${PASS}
    container_name: squid
    volumes:
      - squid-data-folder:/var/spool/squid/
      - ./squid-logs:/var/log/squid
    restart: always
    ports:
      - "3128:3128"
      - "3129:3129"

volumes:
  squid-data-folder: